post http://localhost:3000/auth/sign-up/admin
Content-Type: application/json

{
    "full_name": "Bereket Zeselassie",
    "phone_number": "93",
    "password": " ",
    "language": "eng",
    "admin_level": "Admin",
    "gender": "Male",
    "height": 120,
    "weight": 69,
    "age": 28,
    "activity_status": "Active"

}

###
post http://localhost:3000/auth/sign-in/admin
Content-Type: application/json

{
    "phone_number": "93",
    "password": " "

}

###
get http://localhost:3000/admin/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjU5NjRjNjU3LTFhZjctNDBkMi05N2I5LTE4OGVhMGZjYTVjYiIsInBob25lX251bWJlciI6IjkzIiwiaWF0IjoxNzY4ODEzMTc4fQ.gGfSQrUF5hkHU-XNGpESHVG2BGD1lzHDQQfzTiXgwDM
Content-Type: application/json


###
post http://localhost:3000/auth/sign-up/admin
Content-Type: application/json

{
    "full_name": "Adonay",
    "phone_number": "938792",
    "password": " ",
    "language": "english",
    "admin_level": "admin"
}



###
post http://localhost:3000/admin/membership_plan
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImU2MGU4ZDJiLWUwYWEtNDFlMC1iMThlLTFiNGQ3ZDIxOTRiZSIsInBob25lX251bWJlciI6IjkzIiwiaWF0IjoxNzY5NDIwNjExfQ.HKZjAxz62uUCT9NPpN4Th3ztEhcgJv5tSN1-jo-WvcU

{
    "membership_name": "3 Month",
    "plan_type": "Daily",
    "ticket_amount": 0,
    "duration_days": 90,
    "fee": 1200,
    "description": " ",
    "status": "Active"
}



###
get http://192.168.1.8:3000/admin/members
Content-Type: application/json

###
get http://192.168.1.8:3000/admin/me
Content-Type: application/json

###

post http://localhost:3000/auth/sign-up/member
Content-Type: application/json

{
    "full_name": "k",
    "phone_number": "15",
    "password": " ",
    "language": "English",
    "gender": "Male",
    "height": 120,
    "weight": 69,
    "age": 28,
    "activity_status": "inactive"
}

###
post http://localhost:3000/auth/sign-in/member
Content-Type: application/json

{
    "phone_number": "1234",
    "password": " "

}

###
post http://localhost:3000/member/payment
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjQsInBob25lX251bWJlciI6IjEyMzQiLCJpYXQiOjE3NzAwOTY3Nzd9.iRNgf1eFM6dtIo68sVznSi5d8eHdCw0EwLfz0Q4KIGs

{
    "payment_method": "chapa",
    "amount": "1500",
    "payment_for": "Monthly Membership",
    "membershipPlan_id": "16a5b212-ade9-4289-95b1-302f75843048",
    "payer_id": 24,
    "status": "test",
    "paid_at": "2026-02-24T13:48:36.601Z"
}

###
get http://192.168.1.8:3000/member/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjIsInBob25lX251bWJlciI6IjkzIiwiaWF0IjoxNzY4ODE4Njg3fQ.DWqwvDbAh1BhDQX4H7l-0mL7-nBAAJ-QEd_XZTYKDtg

###

put http://localhost:3000/member/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjIsInBob25lX251bWJlciI6IjkzIiwiaWF0IjoxNzY4ODE4Njg3fQ.DWqwvDbAh1BhDQX4H7l-0mL7-nBAAJ-QEd_XZTYKDtg

{
    "full_name": "bereket zese"
}

