post http://localhost:3000/auth/sign-up/member
Content-Type: application/json

{
    "full_name": "bereket zeselassie",
    "phone_number": "938792",
    "password": " ",
    "language": "eng",
    "admin_level": "admin",
    "gender": "male",
    "height": 120,
    "weight": 69,
    "age": 28,
    "activity_status": "active"

}

###
get http://localhost:3000/admin/me
Content-Type: application/json
Authorization: Bearer asdasdasdas


###
post http://localhost:3000/auth/sign-up/admin
Content-Type: application/json

{
    "full_name": "Adonay",
    "phone_number": "938792",
    "password": " ",
    "language": "english",
    "admin_level": "admin"
}


###
get http://192.168.1.8:3000/admin/members
Content-Type: application/json

